### ISSUE TITLE
Move to rich text editing.

### ISSUE THREAD

**Issue by stuartlynn** [Matico-Platform/matico#166]
The text pane currently uses markdown and a markdown editor for text. This is great but a bit limiting. We should move to using rich text as a way to give better formatting. 

[Verbum](https://github.com/ozanyurtsever/verbum) seems like at good editor solution which uses the [lexical](https://github.com/facebook/lexical) framework under the hood. 

Steps here are 

- [ ] Explore the available plugins for verbum. Things we would want to support are equations, links, images, embeds etc 
- [ ] Switch out the editor and presenter text panes to use verbum and lexical.
- [ ] Allow text to be edited in place rather than in the side bar.

**Comment by nofurtherinformation** [comment]
Resolved in #174
