### ISSUE TITLE
Quality of Life Issues

### ISSUE THREAD

**Issue by nofurtherinformation** [Matico-Platform/matico#46]
- [x] Delete buttons on APIs, Datasets, Apps, Layers, etc.
- [x] Table widths on import API / components
- [x] Geojson/json disambiguation
- [x] Histogram baselines
- [x] Editor sidebar layout tweaks
- [x] Styling panes breathing
- [x] Login error frontend warnings
- [ ] Histogram baseline fix (0 vs non-zero min value)
- [x] Basic control components
- [x] Logging (low priority)

**Comment by stuartlynn** [comment]
This is mostly done. Need some tweak to charts but will open these in a new ticket
